#! /usr/bin/env python3
import random

def main_Menu():
    play = str(input("Do you want to play a game?")
    play = play.lower()
    if ((play == 'yes') or (play == 'y')):
        name = str(input("What name would you like to go by?\n"))
        userChoice = getChoice()
        npcChoice = npc_choice()
        start_game(choice)
        file_output(name)
    else:
        print("Cya")
        quit()
            
def getChoice():
    Int_userChoice = 0
    userChoice = str(input("Choose rock, paper, or scissors\t"))
    userChoice = userChoice.lower()
    if userChoice == "rock":
        Int_userChoice = 1
    elif userChoice == "paper":
        Int_userChoice = 2
    elif userChoice == 'scissors':
        Int_userChoice = 3
    else:
        print("Invalid input, try again.\n")
        getChoice()
    
    return Int_userChoice
            
def npc_choice():
    r = random.SystemRandom()
    npc = r.randint(1, 3)
    return npc
    
def compare_choices(npcChoice, userChoice):
    #rock logic
    if userChoice == 1:
        if npcChoice == 1:
            result = 'Draw'
        elif npcChoice == 2:
            result = 'Loss'
        else:
            result = 'Victory'
    #paper logic
    elif userChoice == 2:
        if npcChoice == 1:
            result = 'Victory!'
        elif npcChoice == 2:
            result = 'Draw'
        else:
            result = 'Loss'
    #scissors logic
    elif userChoice == 3:
        if npcChoice == 1:
            result = 'Loss'
        elif npcChoice == 2:
            result = 'Victory!'
        else:
            result = 'Draw'



    return result            

def start_game(choice):
    if choice == 1:
        name = input("What name would you like to go by?\n")
        # use name for filename
        actual_game(name)
        
    elif choice == 2:
        print("I guess you are too scared to lose, maybe next time.")
        exit()
    
    else:
        print("That isn't a valid option bub...")
        main_Menu()

def actual_game(name):
    #get that game number from some function elsewhere
    while True:
        print("***Game Number: (game num)***")
        print("1 for Rock, 2 for Paper, 3 for Scissors")
        usrChoice = input("---> ")
        try:
            usrChoice = int(usrChoice)
            pass
            #continue into game stuff
        except ValueError:
            print("Hey pick one of those options...")

def main():
    main_Menu()

main()
